### ISSUE TITLE
The problem of the dataset

### ISSUE THREAD

**Issue by angelailei** [Jathurshan0330/Cross-Modal-Transformer#1]
hello, what bothers me is that I don't know the exact form and format of the sleepEDF dataset, can you explain how to apply the dataset

**Comment by Jathurshan0330** [comment]
hi, we have added the data preparations scripts under folder /data_preparations. These scripts can be used to generate the datasets. The dataset is separated into 5 sets (5-fold validation), where subjects in each set are independent. Then the above script extracts data for each channel. You could change the channel to "eog" and other PSG channels to extact data separately.

**Comment by angelailei** [comment]
Thankyou sincerely for my problem, but i was still geting error when trying to run the .py, and i use the default sleep-EDF databast including .EDF files. Is this the problems?

###
/headless/anaconda3/envs/env1-pt/bin/python "/home/EEG test/Cross-Modal-Transformer-master/cmt_training.py"
Torch Version : 1.7.0
Training    Arguements ====================================>
    project_path :  ./results/
    data_path :  .datasets/sleep-telemetry/
    train_data_list :  [0, 1, 2, 3]
    val_data_list :  [4]
    is_retrain :  False
    model_path :  
    save_model_freq :  50
    model_type :  Epoch
    d_model :  256
    dim_feedforward :  1024
    window_size :  50
    num_seq :  5
    batch_size :  32
    weigths :  [1.0, 2.0, 1.0, 2.0, 2.0]
    lr :  0.001
    beta_1 :  0.9
    beta_2 :  0.999
    eps :  1e-09
    weight_decay :  0.0001
    n_epochs :  200
    step_size :  30
    gamma :  0.5
    is_neptune :  False
    nep_project :  
    nep_api :  
Project directory already available at ./results/
Getting Dataset ===================================>
Traceback (most recent call last):
  File "/home/EEG test/Cross-Modal-Transformer-master/cmt_training.py", line 158, in <module>
    main()
  File "/home/EEG test/Cross-Modal-Transformer-master/cmt_training.py", line 94, in main
    train_data_loader, val_data_loader = get_dataset(device, args)
  File "/home/EEG test/Cross-Modal-Transformer-master/datasets/sleep_edf.py", line 198, in get_dataset
    args.train_data_list = list(args.train_data_list[0])
TypeError: 'int' object is not iterable

###
