### ISSUE TITLE
Issue for cmt_training.py

### ISSUE THREAD

**Issue by ting-chuan-wang** [Jathurshan0330/Cross-Modal-Transformer#6]
I run your code, and got an error, please help me.  Thank you.

python cmt_training.py --project_path "./results/0927/" --data_path "/home/tingw/mne_data/physionet-sleep-data/multi_epoch/" --train_data_list [0,1,2,3] --val_data_list [4]  --model_type "Seq" 

The error message is,
Traceback (most recent call last):
  File "/home/tingw/CMTrans/Cross-Modal-Transformer/cmt_training.py", line 155, in <module>
    main()
  File "/home/tingw/CMTrans/Cross-Modal-Transformer/cmt_training.py", line 92, in main
    train_data_loader, val_data_loader = get_dataset(device,args)
  File "/home/tingw/CMTrans/Cross-Modal-Transformer/datasets/sleep_edf.py", line 412, in get_dataset
    train_dataset = SleepEDF_Seq_MultiChan_Dataset_Main(eeg_file = train_eeg_list , 
  File "/home/tingw/CMTrans/Cross-Modal-Transformer/datasets/sleep_edf.py", line 223, in __init__
    bin_labels = np.bincount(self.labels)
ValueError: object too deep for desired array

== LOG below == 
Torch Version : 1.10.0+cu113
Training    Arguements ====================================>
    project_path :  ./results/0927/
    data_path :  /home/tingw/mne_data/physionet-sleep-data/multi_epoch/
    train_data_list :  ['[0,1,2,3]']
    val_data_list :  ['[4]']
    is_retrain :  False
    model_path :  
    save_model_freq :  50
    model_type :  Seq
    d_model :  128
    dim_feedforward :  512
    window_size :  50
    num_seq :  15
    batch_size :  32
    weigths :  [1.0, 2.0, 1.0, 2.0, 2.0]
    lr :  0.001
    beta_1 :  0.9
    beta_2 :  0.999
    eps :  1e-09
    weight_decay :  0.0001
    n_epochs :  200
    step_size :  30
    gamma :  0.5
    is_neptune :  False
    nep_project :  
    nep_api :  
Project directory created at ./results/0927/
Getting Dataset ===================================>
['/home/tingw/mne_data/physionet-sleep-data/multi_epoch/x1.h5', '/home/tingw/mne_data/physionet-sleep-data/multi_epoch/x2.h5', '/home/tingw/mne_data/physionet-sleep-data/multi_epoch/x3.h5', '/home/tingw/mne_data/physionet-sleep-data/multi_epoch/x4.h5', '/home/tingw/mne_data/physionet-sleep-data/multi_epoch/x5.h5']
Training Data Files: ===========================>
['/home/tingw/mne_data/physionet-sleep-data/multi_epoch/x1.h5'
 '/home/tingw/mne_data/physionet-sleep-data/multi_epoch/x2.h5'
 '/home/tingw/mne_data/physionet-sleep-data/multi_epoch/x3.h5'
 '/home/tingw/mne_data/physionet-sleep-data/multi_epoch/x4.h5']
['/home/tingw/mne_data/physionet-sleep-data/multi_epoch/eog1.h5'
 '/home/tingw/mne_data/physionet-sleep-data/multi_epoch/eog2.h5'
 '/home/tingw/mne_data/physionet-sleep-data/multi_epoch/eog3.h5'
 '/home/tingw/mne_data/physionet-sleep-data/multi_epoch/eog4.h5']
['/home/tingw/mne_data/physionet-sleep-data/multi_epoch/y1.h5'
 '/home/tingw/mne_data/physionet-sleep-data/multi_epoch/y2.h5'
 '/home/tingw/mne_data/physionet-sleep-data/multi_epoch/y3.h5'
 '/home/tingw/mne_data/physionet-sleep-data/multi_epoch/y4.h5']
['/home/tingw/mne_data/physionet-sleep-data/multi_epoch/mean1.h5'
 '/home/tingw/mne_data/physionet-sleep-data/multi_epoch/mean2.h5'
 '/home/tingw/mne_data/physionet-sleep-data/multi_epoch/mean3.h5'
 '/home/tingw/mne_data/physionet-sleep-data/multi_epoch/mean4.h5']
['/home/tingw/mne_data/physionet-sleep-data/multi_epoch/std1.h5'
 '/home/tingw/mne_data/physionet-sleep-data/multi_epoch/std2.h5'
 '/home/tingw/mne_data/physionet-sleep-data/multi_epoch/std3.h5'
 '/home/tingw/mne_data/physionet-sleep-data/multi_epoch/std4.h5']
['/home/tingw/mne_data/physionet-sleep-data/multi_epoch/eog_m1.h5'
 '/home/tingw/mne_data/physionet-sleep-data/multi_epoch/eog_m2.h5'
 '/home/tingw/mne_data/physionet-sleep-data/multi_epoch/eog_m3.h5'
 '/home/tingw/mne_data/physionet-sleep-data/multi_epoch/eog_m4.h5']
['/home/tingw/mne_data/physionet-sleep-data/multi_epoch/eog_std1.h5'
 '/home/tingw/mne_data/physionet-sleep-data/multi_epoch/eog_std2.h5'
 '/home/tingw/mne_data/physionet-sleep-data/multi_epoch/eog_std3.h5'
 '/home/tingw/mne_data/physionet-sleep-data/multi_epoch/eog_std4.h5']
Validation Data Files: ===========================>
['/home/tingw/mne_data/physionet-sleep-data/multi_epoch/x5.h5']
['/home/tingw/mne_data/physionet-sleep-data/multi_epoch/eog5.h5']
['/home/tingw/mne_data/physionet-sleep-data/multi_epoch/y5.h5']
['/home/tingw/mne_data/physionet-sleep-data/multi_epoch/mean5.h5']
['/home/tingw/mne_data/physionet-sleep-data/multi_epoch/std5.h5']
['/home/tingw/mne_data/physionet-sleep-data/multi_epoch/eog_m5.h5']
['/home/tingw/mne_data/physionet-sleep-data/multi_epoch/eog_std5.h5']
Loading Train Data for many-to-many classification ==================================>
Reading from /home/tingw/mne_data/physionet-sleep-data/multi_epoch/x1.h5 ====================================================
Keys in the h5py file : <KeysViewHDF5 ['data']>
Number of samples : 43455
Shape of each data : (43455, 5, 3000)
Reading from /home/tingw/mne_data/physionet-sleep-data/multi_epoch/eog1.h5 ====================================================
Keys in the h5py file : <KeysViewHDF5 ['data']>
Number of samples : 43455
Shape of each data : (43455, 5, 3000)
Reading from /home/tingw/mne_data/physionet-sleep-data/multi_epoch/y1.h5 ====================================================
Keys in the h5py file : <KeysViewHDF5 ['data']>
Number of samples : 43455
Shape of each data : (43455, 5)
Reading from /home/tingw/mne_data/physionet-sleep-data/multi_epoch/x2.h5 ====================================================
Keys in the h5py file : <KeysViewHDF5 ['data']>
Number of samples : 39919
Shape of each data : (39919, 5, 3000)
Reading from /home/tingw/mne_data/physionet-sleep-data/multi_epoch/eog2.h5 ====================================================
Keys in the h5py file : <KeysViewHDF5 ['data']>
Number of samples : 39919
Shape of each data : (39919, 5, 3000)
Reading from /home/tingw/mne_data/physionet-sleep-data/multi_epoch/y2.h5 ====================================================
Keys in the h5py file : <KeysViewHDF5 ['data']>
Number of samples : 39919
Shape of each data : (39919, 5)
Reading from /home/tingw/mne_data/physionet-sleep-data/multi_epoch/x3.h5 ====================================================
Keys in the h5py file : <KeysViewHDF5 ['data']>
Number of samples : 35112
Shape of each data : (35112, 5, 3000)
Reading from /home/tingw/mne_data/physionet-sleep-data/multi_epoch/eog3.h5 ====================================================
Keys in the h5py file : <KeysViewHDF5 ['data']>
Number of samples : 35112
Shape of each data : (35112, 5, 3000)
Reading from /home/tingw/mne_data/physionet-sleep-data/multi_epoch/y3.h5 ====================================================
Keys in the h5py file : <KeysViewHDF5 ['data']>
Number of samples : 35112
Shape of each data : (35112, 5)
Reading from /home/tingw/mne_data/physionet-sleep-data/multi_epoch/x4.h5 ====================================================
Keys in the h5py file : <KeysViewHDF5 ['data']>
Number of samples : 40211
Shape of each data : (40211, 5, 3000)
Reading from /home/tingw/mne_data/physionet-sleep-data/multi_epoch/eog4.h5 ====================================================
Keys in the h5py file : <KeysViewHDF5 ['data']>
Number of samples : 40211
Shape of each data : (40211, 5, 3000)
Reading from /home/tingw/mne_data/physionet-sleep-data/multi_epoch/y4.h5 ====================================================
Keys in the h5py file : <KeysViewHDF5 ['data']>
Number of samples : 40211
Shape of each data : (40211, 5)
Traceback (most recent call last):
  File "/home/tingw/CMTrans/Cross-Modal-Transformer/cmt_training.py", line 155, in <module>
    main()
  File "/home/tingw/CMTrans/Cross-Modal-Transformer/cmt_training.py", line 92, in main
    train_data_loader, val_data_loader = get_dataset(device,args)
  File "/home/tingw/CMTrans/Cross-Modal-Transformer/datasets/sleep_edf.py", line 412, in get_dataset
    train_dataset = SleepEDF_Seq_MultiChan_Dataset_Main(eeg_file = train_eeg_list , 
  File "/home/tingw/CMTrans/Cross-Modal-Transformer/datasets/sleep_edf.py", line 223, in __init__
    bin_labels = np.bincount(self.labels)
ValueError: object too deep for desired array

**Comment by Jathurshan0330** [comment]
Can you comment out the bin_labels? It is there to check the counts of different classes. I hope it works

**Comment by ting-chuan-wang** [comment]
Thanks.  
I commented out the bin_labels.  Now it stops at another place.
    b,_, _ = x.shape  
ValueError: too many values to unpack (expected 3)

Below I found the issue is that x.shape become 4D data:
def forward(self, x: Tensor) -> Tensor:
        print(">>> forward() In shape: ", x.shape)    ### [32, 3000, 5]
        if x.shape[0]!=1:
            x = x.squeeze().unsqueeze(dim = 1)        ### output [32, 1, 3000, 5]

If I change it to 
    b,_, _, _ = x.shape 
The next line is not working.
    x_1 = self.projection_1(x)

Please help.  Thanks.

== LOG below == 
Torch Version : 1.10.0+cu113
Training    Arguements ====================================>
    project_path :  ./results/0930/
    data_path :  /home/tingw/mne_data/physionet-sleep-data/multi_epoch/
    train_data_list :  ['[0,1,2,3]']
    val_data_list :  ['[4]']
    is_retrain :  False
    model_path :  
    save_model_freq :  50
    model_type :  Seq
    d_model :  128
    dim_feedforward :  512
    window_size :  50
    num_seq :  15
    batch_size :  32
    weigths :  [1.0, 2.0, 1.0, 2.0, 2.0]
    lr :  0.001
    beta_1 :  0.9
    beta_2 :  0.999
    eps :  1e-09
    weight_decay :  0.0001
    n_epochs :  200
    step_size :  30
    gamma :  0.5
    is_neptune :  False
    nep_project :  
    nep_api :  
Project directory already available at ./results/0930/
Getting Dataset ===================================>
['/home/tingw/mne_data/physionet-sleep-data/multi_epoch/x1.h5', '/home/tingw/mne_data/physionet-sleep-data/multi_epoch/x2.h5', '/home/tingw/mne_data/physionet-sleep-data/multi_epoch/x3.h5', '/home/tingw/mne_data/physionet-sleep-data/multi_epoch/x4.h5', '/home/tingw/mne_data/physionet-sleep-data/multi_epoch/x5.h5']
Training Data Files: ===========================>
['/home/tingw/mne_data/physionet-sleep-data/multi_epoch/x1.h5'
 '/home/tingw/mne_data/physionet-sleep-data/multi_epoch/x2.h5'
 '/home/tingw/mne_data/physionet-sleep-data/multi_epoch/x3.h5'
 '/home/tingw/mne_data/physionet-sleep-data/multi_epoch/x4.h5']
['/home/tingw/mne_data/physionet-sleep-data/multi_epoch/eog1.h5'
 '/home/tingw/mne_data/physionet-sleep-data/multi_epoch/eog2.h5'
 '/home/tingw/mne_data/physionet-sleep-data/multi_epoch/eog3.h5'
 '/home/tingw/mne_data/physionet-sleep-data/multi_epoch/eog4.h5']
['/home/tingw/mne_data/physionet-sleep-data/multi_epoch/y1.h5'
 '/home/tingw/mne_data/physionet-sleep-data/multi_epoch/y2.h5'
 '/home/tingw/mne_data/physionet-sleep-data/multi_epoch/y3.h5'
 '/home/tingw/mne_data/physionet-sleep-data/multi_epoch/y4.h5']
['/home/tingw/mne_data/physionet-sleep-data/multi_epoch/mean1.h5'
 '/home/tingw/mne_data/physionet-sleep-data/multi_epoch/mean2.h5'
 '/home/tingw/mne_data/physionet-sleep-data/multi_epoch/mean3.h5'
 '/home/tingw/mne_data/physionet-sleep-data/multi_epoch/mean4.h5']
['/home/tingw/mne_data/physionet-sleep-data/multi_epoch/std1.h5'
 '/home/tingw/mne_data/physionet-sleep-data/multi_epoch/std2.h5'
 '/home/tingw/mne_data/physionet-sleep-data/multi_epoch/std3.h5'
 '/home/tingw/mne_data/physionet-sleep-data/multi_epoch/std4.h5']
['/home/tingw/mne_data/physionet-sleep-data/multi_epoch/eog_m1.h5'
 '/home/tingw/mne_data/physionet-sleep-data/multi_epoch/eog_m2.h5'
 '/home/tingw/mne_data/physionet-sleep-data/multi_epoch/eog_m3.h5'
 '/home/tingw/mne_data/physionet-sleep-data/multi_epoch/eog_m4.h5']
['/home/tingw/mne_data/physionet-sleep-data/multi_epoch/eog_std1.h5'
 '/home/tingw/mne_data/physionet-sleep-data/multi_epoch/eog_std2.h5'
 '/home/tingw/mne_data/physionet-sleep-data/multi_epoch/eog_std3.h5'
 '/home/tingw/mne_data/physionet-sleep-data/multi_epoch/eog_std4.h5']
Validation Data Files: ===========================>
['/home/tingw/mne_data/physionet-sleep-data/multi_epoch/x5.h5']
['/home/tingw/mne_data/physionet-sleep-data/multi_epoch/eog5.h5']
['/home/tingw/mne_data/physionet-sleep-data/multi_epoch/y5.h5']
['/home/tingw/mne_data/physionet-sleep-data/multi_epoch/mean5.h5']
['/home/tingw/mne_data/physionet-sleep-data/multi_epoch/std5.h5']
['/home/tingw/mne_data/physionet-sleep-data/multi_epoch/eog_m5.h5']
['/home/tingw/mne_data/physionet-sleep-data/multi_epoch/eog_std5.h5']
Loading Train Data for many-to-many classification ==================================>
Reading from /home/tingw/mne_data/physionet-sleep-data/multi_epoch/x1.h5 ====================================================
Keys in the h5py file : <KeysViewHDF5 ['data']>
Number of samples : 43455
Shape of each data : (43455, 5, 3000)
Reading from /home/tingw/mne_data/physionet-sleep-data/multi_epoch/eog1.h5 ====================================================
Keys in the h5py file : <KeysViewHDF5 ['data']>
Number of samples : 43455
Shape of each data : (43455, 5, 3000)
Reading from /home/tingw/mne_data/physionet-sleep-data/multi_epoch/y1.h5 ====================================================
Keys in the h5py file : <KeysViewHDF5 ['data']>
Number of samples : 43455
Shape of each data : (43455, 5)
Reading from /home/tingw/mne_data/physionet-sleep-data/multi_epoch/x2.h5 ====================================================
Keys in the h5py file : <KeysViewHDF5 ['data']>
Number of samples : 39919
Shape of each data : (39919, 5, 3000)
Reading from /home/tingw/mne_data/physionet-sleep-data/multi_epoch/eog2.h5 ====================================================
Keys in the h5py file : <KeysViewHDF5 ['data']>
Number of samples : 39919
Shape of each data : (39919, 5, 3000)
Reading from /home/tingw/mne_data/physionet-sleep-data/multi_epoch/y2.h5 ====================================================
Keys in the h5py file : <KeysViewHDF5 ['data']>
Number of samples : 39919
Shape of each data : (39919, 5)
Reading from /home/tingw/mne_data/physionet-sleep-data/multi_epoch/x3.h5 ====================================================
Keys in the h5py file : <KeysViewHDF5 ['data']>
Number of samples : 35112
Shape of each data : (35112, 5, 3000)
Reading from /home/tingw/mne_data/physionet-sleep-data/multi_epoch/eog3.h5 ====================================================
Keys in the h5py file : <KeysViewHDF5 ['data']>
Number of samples : 35112
Shape of each data : (35112, 5, 3000)
Reading from /home/tingw/mne_data/physionet-sleep-data/multi_epoch/y3.h5 ====================================================
Keys in the h5py file : <KeysViewHDF5 ['data']>
Number of samples : 35112
Shape of each data : (35112, 5)
Reading from /home/tingw/mne_data/physionet-sleep-data/multi_epoch/x4.h5 ====================================================
Keys in the h5py file : <KeysViewHDF5 ['data']>
Number of samples : 40211
Shape of each data : (40211, 5, 3000)
Reading from /home/tingw/mne_data/physionet-sleep-data/multi_epoch/eog4.h5 ====================================================
Keys in the h5py file : <KeysViewHDF5 ['data']>
Number of samples : 40211
Shape of each data : (40211, 5, 3000)
Reading from /home/tingw/mne_data/physionet-sleep-data/multi_epoch/y4.h5 ====================================================
Keys in the h5py file : <KeysViewHDF5 ['data']>
Number of samples : 40211
Shape of each data : (40211, 5)
Shape of EEG : (158697, 5, 3000) , EOG : (158697, 5, 3000)
Shape of Labels : torch.Size([158697, 5])
Reading Subject wise mean and sd
Reading from /home/tingw/mne_data/physionet-sleep-data/multi_epoch/mean1.h5 ====================================================
Keys in the h5py file : <KeysViewHDF5 ['data']>
Number of samples : 43455
Shape of each data : (43455,)
Reading from /home/tingw/mne_data/physionet-sleep-data/multi_epoch/std1.h5 ====================================================
Keys in the h5py file : <KeysViewHDF5 ['data']>
Number of samples : 43455
Shape of each data : (43455,)
Reading from /home/tingw/mne_data/physionet-sleep-data/multi_epoch/eog_m1.h5 ====================================================
Keys in the h5py file : <KeysViewHDF5 ['data']>
Number of samples : 43455
Shape of each data : (43455,)
Reading from /home/tingw/mne_data/physionet-sleep-data/multi_epoch/eog_std1.h5 ====================================================
Keys in the h5py file : <KeysViewHDF5 ['data']>
Number of samples : 43455
Shape of each data : (43455,)
Reading from /home/tingw/mne_data/physionet-sleep-data/multi_epoch/mean2.h5 ====================================================
Keys in the h5py file : <KeysViewHDF5 ['data']>
Number of samples : 39919
Shape of each data : (39919,)
Reading from /home/tingw/mne_data/physionet-sleep-data/multi_epoch/std2.h5 ====================================================
Keys in the h5py file : <KeysViewHDF5 ['data']>
Number of samples : 39919
Shape of each data : (39919,)
Reading from /home/tingw/mne_data/physionet-sleep-data/multi_epoch/eog_m2.h5 ====================================================
Keys in the h5py file : <KeysViewHDF5 ['data']>
Number of samples : 39919
Shape of each data : (39919,)
Reading from /home/tingw/mne_data/physionet-sleep-data/multi_epoch/eog_std2.h5 ====================================================
Keys in the h5py file : <KeysViewHDF5 ['data']>
Number of samples : 39919
Shape of each data : (39919,)
Reading from /home/tingw/mne_data/physionet-sleep-data/multi_epoch/mean3.h5 ====================================================
Keys in the h5py file : <KeysViewHDF5 ['data']>
Number of samples : 35112
Shape of each data : (35112,)
Reading from /home/tingw/mne_data/physionet-sleep-data/multi_epoch/std3.h5 ====================================================
Keys in the h5py file : <KeysViewHDF5 ['data']>
Number of samples : 35112
Shape of each data : (35112,)
Reading from /home/tingw/mne_data/physionet-sleep-data/multi_epoch/eog_m3.h5 ====================================================
Keys in the h5py file : <KeysViewHDF5 ['data']>
Number of samples : 35112
Shape of each data : (35112,)
Reading from /home/tingw/mne_data/physionet-sleep-data/multi_epoch/eog_std3.h5 ====================================================
Keys in the h5py file : <KeysViewHDF5 ['data']>
Number of samples : 35112
Shape of each data : (35112,)
Reading from /home/tingw/mne_data/physionet-sleep-data/multi_epoch/mean4.h5 ====================================================
Keys in the h5py file : <KeysViewHDF5 ['data']>
Number of samples : 40211
Shape of each data : (40211,)
Reading from /home/tingw/mne_data/physionet-sleep-data/multi_epoch/std4.h5 ====================================================
Keys in the h5py file : <KeysViewHDF5 ['data']>
Number of samples : 40211
Shape of each data : (40211,)
Reading from /home/tingw/mne_data/physionet-sleep-data/multi_epoch/eog_m4.h5 ====================================================
Keys in the h5py file : <KeysViewHDF5 ['data']>
Number of samples : 40211
Shape of each data : (40211,)
Reading from /home/tingw/mne_data/physionet-sleep-data/multi_epoch/eog_std4.h5 ====================================================
Keys in the h5py file : <KeysViewHDF5 ['data']>
Number of samples : 40211
Shape of each data : (40211,)
Shapes of Mean  : EEG: (158697,), EOG : (158697,)
Shapes of Sd  : EEG: (158697,), EOG : (158697,)
Loading Val Data for many-to-many classification ==================================>
Reading from /home/tingw/mne_data/physionet-sleep-data/multi_epoch/x5.h5 ====================================================
Keys in the h5py file : <KeysViewHDF5 ['data']>
Number of samples : 36485
Shape of each data : (36485, 5, 3000)
Reading from /home/tingw/mne_data/physionet-sleep-data/multi_epoch/eog5.h5 ====================================================
Keys in the h5py file : <KeysViewHDF5 ['data']>
Number of samples : 36485
Shape of each data : (36485, 5, 3000)
Reading from /home/tingw/mne_data/physionet-sleep-data/multi_epoch/y5.h5 ====================================================
Keys in the h5py file : <KeysViewHDF5 ['data']>
Number of samples : 36485
Shape of each data : (36485, 5)
Shape of EEG : (36485, 5, 3000) , EOG : (36485, 5, 3000)
Shape of Labels : torch.Size([36485, 5])
Reading Subject wise mean and sd
Reading from /home/tingw/mne_data/physionet-sleep-data/multi_epoch/mean5.h5 ====================================================
Keys in the h5py file : <KeysViewHDF5 ['data']>
Number of samples : 36485
Shape of each data : (36485,)
Reading from /home/tingw/mne_data/physionet-sleep-data/multi_epoch/std5.h5 ====================================================
Keys in the h5py file : <KeysViewHDF5 ['data']>
Number of samples : 36485
Shape of each data : (36485,)
Reading from /home/tingw/mne_data/physionet-sleep-data/multi_epoch/eog_m5.h5 ====================================================
Keys in the h5py file : <KeysViewHDF5 ['data']>
Number of samples : 36485
Shape of each data : (36485,)
Reading from /home/tingw/mne_data/physionet-sleep-data/multi_epoch/eog_std5.h5 ====================================================
Keys in the h5py file : <KeysViewHDF5 ['data']>
Number of samples : 36485
Shape of each data : (36485,)
Shapes of Mean  : EEG: (36485,), EOG : (36485,)
Shapes of Sd  : EEG: (36485,), EOG : (36485,)
EEG batch shape: torch.Size([32, 3000, 15, 5])
EOG batch shape: torch.Size([32, 3000, 15, 5])
Labels batch shape: torch.Size([32, 15, 5])
EEG batch shape: torch.Size([32, 3000, 15, 5])
EOG batch shape: torch.Size([32, 3000, 15, 5])
Labels batch shape: torch.Size([32, 15, 5])
EEG Minimum :-11.41333721330944
EEG Maximum :11.627864012828486
EOG Minimum :-13.291103170514944
EOG Maximum :12.179615041092605
EEG Mean :-9.066378188759094e-05
EEG Standard Deviation :0.9713700974582382
EOG Mean :4.682988494505859e-05
EOG Standard Deviation :0.9103014239304752
Initializing Sequence Cross Modal Transformer ==================>
============================= Training Epoch : [1/200]===============================>
>>> forward() In shape:  torch.Size([32, 3000, 5])
>>> forward() shape:  torch.Size([32, 1, 3000, 5])
Traceback (most recent call last):
  File "/home/tingw/CMTrans/Cross-Modal-Transformer/cmt_training.py", line 155, in <module>
    main()
  File "/home/tingw/CMTrans/Cross-Modal-Transformer/cmt_training.py", line 152, in main
    train_seq_cmt(Net, train_data_loader, val_data_loader, criterion, optimizer, lr_scheduler, device, args)  
  File "/home/tingw/CMTrans/Cross-Modal-Transformer/models/sequence_cmt.py", line 328, in train_seq_cmt
    outputs,_ = Net(eeg.float().to(device), eog.float().to(device))
  File "/home/tingw/anaconda3/envs/CMTrans/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/tingw/CMTrans/Cross-Modal-Transformer/models/sequence_cmt.py", line 196, in forward
    epoch_1,feat_1 = self.epoch_1(eeg[:,:,0,:],eog[:,:,0,:])#[0]
  File "/home/tingw/anaconda3/envs/CMTrans/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/tingw/CMTrans/Cross-Modal-Transformer/models/sequence_cmt.py", line 39, in forward
    self_eeg = self.eeg_atten(eeg)
  File "/home/tingw/anaconda3/envs/CMTrans/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/tingw/CMTrans/Cross-Modal-Transformer/models/model_blocks.py", line 147, in forward
    src = self.window_embed(x)
  File "/home/tingw/anaconda3/envs/CMTrans/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/tingw/CMTrans/Cross-Modal-Transformer/models/model_blocks.py", line 107, in forward
    b,_, _ = x.shape  
ValueError: too many values to unpack (expected 3)

**Comment by Jathurshan0330** [comment]
x should be three dimensional, can you share the shape of x given as input

**Comment by ting-chuan-wang** [comment]
The input x was  [32, 3000, 5]
but 
   x = x.squeeze().unsqueeze(dim = 1) 
change it to 4D [32, 1, 3000, 5]

**Comment by Yumi0606** [comment]
same problem,
Our team is reproducing the seq_model. However, when using the dataset processed by `muti_epoch.py`, we encounter this error. But the dataset processed by `single_epoch.py` can be used for training both the epoch_model and seq_model. So, is muti_epoch.py error-free?
